/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./*.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tertiary": "#442b00",
                "surface-deep": "#111111",
                "tertiary-container": "#c48400",
                "on-secondary-fixed": "#001f24",
                "inverse-primary": "#c00018",
                "secondary-fixed-dim": "#00daf3",
                "surface-tint": "#ffb3ac",
                "primary": "#ffb3ac",
                "tertiary": "#ffba4b",
                "on-primary-fixed": "#410003",
                "status-warning": "#FFB020",
                "on-error-container": "#ffdad6",
                "secondary": "#bdf4ff",
                "error-container": "#93000a",
                "tertiary-fixed": "#ffddb1",
                "surface-container-lowest": "#0e0e0e",
                "secondary-container": "#00e3fd",
                "on-secondary-container": "#00616d",
                "outline": "#ad8884",
                "inverse-on-surface": "#313030",
                "status-error": "#FF3B3B",
                "surface-dim": "#131313",
                "tertiary-fixed-dim": "#ffba4b",
                "on-error": "#690005",
                "on-surface": "#e5e2e1",
                "status-cyan": "#00E5FF",
                "status-success": "#34C759",
                "surface-container-low": "#1c1b1b",
                "on-secondary-fixed-variant": "#004f58",
                "surface-container-highest": "#353534",
                "on-primary-container": "#5c0006",
                "outline-variant": "#5d3f3c",
                "on-tertiary-fixed": "#291800",
                "surface": "#131313",
                "on-primary-fixed-variant": "#930010",
                "on-primary": "#680008",
                "surface-container": "#201f1f",
                "text-medium": "#BDBDBD",
                "background": "#131313",
                "primary-fixed-dim": "#ffb3ac",
                "secondary-fixed": "#9cf0ff",
                "primary-fixed": "#ffdad6",
                "on-background": "#e5e2e1",
                "on-tertiary-fixed-variant": "#624000",
                "primary-container": "#ff544e",
                "inverse-surface": "#e5e2e1",
                "surface-container-high": "#2a2a2a",
                "surface-elevated": "#1C1C1C",
                "on-secondary": "#00363d",
                "surface-bright": "#393939",
                "on-tertiary-container": "#3b2500",
                "text-low": "#7E7E7E",
                "error": "#ffb4ab",
                "on-surface-variant": "#e6bdb9",
                "surface-variant": "#353534",
                "text-high": "#FFFFFF"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "xl": "32px",
                "container-max": "1200px",
                "4xl": "96px",
                "3xl": "64px",
                "base": "8px",
                "lg": "24px",
                "gutter": "24px",
                "sm": "8px",
                "margin-mobile": "24px",
                "xxl": "48px",
                "xs": "4px",
                "md": "16px"
            },
            "fontFamily": {
                "label-md": ["Poppins"],
                "title-lg": ["Poppins"],
                "body-lg": ["Poppins"],
                "headline-sm": ["Poppins"],
                "headline-lg": ["Poppins"],
                "headline-lg-mobile": ["Poppins"],
                "body-md": ["Poppins"],
                "headline-md": ["Poppins"],
                "headline-xl": ["Poppins"],
                "caption": ["Poppins"]
            },
            "fontSize": {
                "label-md": ["14px", { "lineHeight": "24px", "fontWeight": "400" }],
                "title-lg": ["22px", { "lineHeight": "30px", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "32px", "fontWeight": "400" }],
                "headline-sm": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
                "headline-lg": ["52px", { "lineHeight": "60px", "letterSpacing": "-0.5px", "fontWeight": "700" }],
                "headline-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.5px", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "28px", "fontWeight": "400" }],
                "headline-md": ["40px", { "lineHeight": "48px", "fontWeight": "700" }],
                "headline-xl": ["72px", { "lineHeight": "80px", "letterSpacing": "-1px", "fontWeight": "700" }],
                "caption": ["12px", { "lineHeight": "18px", "fontWeight": "400" }]
            }
        }
    }
}
